# Project 2: Pandas CSV Reader & Basic Analysis

In [1]:
import pandas as pd

## 1. Read/Inspect CSV/Excel file

In [ ]:
df = pd.read_excel('SuperStoreData.xlsx')
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [3]:
df.tail(3)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
9991,9992,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.576,2,0.2,19.3932
9992,9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.600,4,0.0,13.3200
9993,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.160,2,0.0,72.9480

In [4]:
df.shape

(9994, 21)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   datetime64[ns]
 3   Ship Date      9994 non-null   datetime64[ns]
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: datetime64[ns](2), float64(3), int64(3), object(13)
memory usage: 1.6+ MB

In [6]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [7]:
df['State']

0         Kentucky
1         Kentucky
2       California
3          Florida
4          Florida
           ...
9989       Florida
9990    California
9991    California
9992    California
9993    California
Name: State, Length: 9994, dtype: object

## Summary Statistics

In [8]:
df.describe().T

,count,mean,min,25%,50%,75%,max,std
Row ID,9994.0,4997.5,1.0,2499.25,4997.5,7495.75,9994.0,2885.163629
Order Date,9994,2016-04-30 00:07:12.259355648,2014-01-03 00:00:00,2015-05-23 00:00:00,2016-06-26 00:00:00,2017-05-14 00:00:00,2017-12-30 00:00:00,NaN
Ship Date,9994,2016-05-03 23:06:58.571142912,2014-01-07 00:00:00,2015-05-27 00:00:00,2016-06-29 00:00:00,2017-05-18 00:00:00,2018-01-05 00:00:00,NaN
Postal Code,9994.0,55190.379428,1040.0,23223.0,56430.5,90008.0,99301.0,32063.69335
Sales,9994.0,229.858001,0.444,17.28,54.49,209.94,22638.48,623.245101
Quantity,9994.0,3.789574,1.0,2.0,3.0,5.0,14.0,2.22511
Discount,9994.0,0.156203,0.0,0.0,0.2,0.2,0.8,0.206452
Profit,9994.0,28.656896,-6599.978,1.72875,8.6665,29.364,8399.976,234.260108

In [22]:
df['Segment'].value_counts()

Segment
Consumer       5191
Corporate      3020
Home Office    1783
Name: count, dtype: int64

In [21]:
df['Ship Mode'].value_counts()

Ship Mode
Standard Class    5968
Second Class      1945
First Class       1538
Same Day           543
Name: count, dtype: int64

In [ ]:
df['Region'].value_counts()

Region
West       3203
East       2848
Central    2323
South      1620
Name: count, dtype: int64

In [20]:
df['Category'].value_counts()

Category
Office Supplies    6026
Furniture          2121
Technology         1847
Name: count, dtype: int64

## Filters & Slicers

In [10]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [26]:
# Top Categories by Profit
top_cat_profit = df.groupby(['Category'])['Profit'].sum().nlargest(3).reset_index()
top_cat_profit

          Category       Profit
0       Technology  145454.9481
1  Office Supplies  122490.8008
2        Furniture   18451.2728

In [25]:
# What sub-category gained the most profit?
top_sub_profit = df[df['Category'] == "Technology"].groupby('Sub-Category')['Profit'].sum().nlargest(5).reset_index()
top_sub_profit

  Sub-Category      Profit
0      Copiers  55617.8249
1       Phones  44515.7306
2  Accessories  41936.6357
3     Machines   3384.7569

In [24]:
# Top Categories according to Sales
top_categories_sales = df.groupby(['Category'])['Sales'].sum().nlargest(3).reset_index()
top_categories_sales

          Category        Sales
0       Technology  836154.0330
1        Furniture  741999.7953
2  Office Supplies  719047.0320

In [23]:
# What sub-category had the highest sales?
top_sub_sales = df[df['Category'] == "Technology"].groupby('Sub-Category')['Sales'].sum(5).nlargest().reset_index()
top_sub_sales

  Sub-Category       Sales
0       Phones  330007.054
1     Machines  189238.631
2  Accessories  167380.318
3      Copiers  149528.030

In [15]:
# State with the most profit
top_state_profit = df.groupby(['State'])['Profit'].sum().nlargest(10).reset_index()
top_state_profit

        State      Profit
0  California  76381.3871
1    New York  74038.5486
2  Washington  33402.6517
3    Michigan  24463.1876
4    Virginia  18597.9504
5     Indiana  18382.9363
6     Georgia  16250.0433
7    Kentucky  11199.6966
8   Minnesota  10823.1874
9    Delaware   9977.3748

In [16]:
# What State made the most sales?
top_state_sales = df.groupby(['State'])['Sales'].sum().nlargest(10).reset_index()
top_state_sales

          State        Sales
0    California  457687.6315
1      New York  310876.2710
2         Texas  170188.0458
3    Washington  138641.2700
4  Pennsylvania  116511.9140
5       Florida   89473.7080
6      Illinois   80166.1010
7          Ohio   78258.1360
8      Michigan   76269.6140
9      Virginia   70636.7200

In [ ]:
# In the state with the most sales, what city was the highest?
top_city_sales = df[df['State'] == "California"].groupby('City')['Sales'].sum().nlargest(5).reset_index()
top_city_sales

            City        Sales
0    Los Angeles  175851.3410
1  San Francisco  112669.0920
2      San Diego   47521.0290
3        Anaheim    7986.8700
4         Fresno    7888.5285

In [32]:
# Segment with the highest average discount
top_seg_discn = df.groupby("Segment")["Discount"].mean().sort_values(ascending=False).reset_index()
top_seg_discn

       Segment  Discount
0    Corporate  0.158228
1     Consumer  0.158141
2  Home Office  0.147128

In [29]:
# What segment made the most profit?
top_seg_profit = df.groupby(['Segment'])['Profit'].sum().nlargest(3).reset_index()
top_seg_profit

       Segment       Profit
0     Consumer  134119.2092
1    Corporate   91979.1340
2  Home Office   60298.6785

In [33]:
# What Customer accrued the most profit
top_10_customers = df.groupby(['Customer ID', 'Customer Name', 'Segment'])['Profit'].sum().nlargest(10).reset_index()
top_10_customers

  Customer ID         Customer Name      Segment     Profit
0    TC-20980          Tamara Chand    Corporate  8981.3239
1    RB-19360          Raymond Buch     Consumer  6976.0959
2    SC-20095          Sanjit Chand     Consumer  5757.4119
3    HL-15040          Hunter Lopez     Consumer  5622.4292
4    AB-10105         Adrian Barton     Consumer  5444.8055
5    TA-21385          Tom Ashbrook  Home Office  4703.7883
6    CM-12385  Christopher Martinez     Consumer  3899.8904
7    KD-16495         Keith Dawkins    Corporate  3038.6254
8    AR-10540           Andy Reiter     Consumer  2884.6208
9    DR-12940         Daniel Raglin  Home Office  2869.0760

## Save Filtered Results

In [34]:
# 1
top_cat_profit.to_csv("top_category_by_profit.csv", index=False)
# 2
top_sub_profit.to_csv("subcategory_by_profit.csv", index=False)
# 3
top_categories_sales.to_csv("top_category_by_sales.csv", index=False)
# 4
top_sub_sales.to_csv("subcategory_by_sales.csv", index=False)
# 5
top_state_profit.to_csv("top_state_by_profit.csv", index=False)
# 6
top_state_sales.to_csv("top_state_by_sales.csv", index=False)
# 7
top_city_sales.to_csv("top_city_by_sales.csv", index=False)
# 8
top_seg_discn.to_csv("top_segment_by_discount.csv", index=False)
# 9
top_seg_profit.to_csv("top_segment_by_profit.csv", index=False)
# 10
top_10_customers.to_csv("top_10_customers_profit.csv", index=False)